# Input data and output locations
output_dir: '/users/k2260401/alspac/am/results'

linker_file: '/users/k2260401/alspac/am/data/linker_file.csv'  # maps ids in bgen files to contributor ids (cids)
include_cids_file: '/users/k2260401/alspac/am/data/include_ids.txt'
gwas_file: '/users/k2260401/alspac/am/data/gwas.tsv'

data_dirs:
  gi_1000g_g0p:
    bgen_dir: '/users/k2260401/alspac/genetics/gi_1000g_g0p/dosage_bgen'
    sample_file: '/users/k2260401/alspac/genetics/gi_1000g_g0p/swapped.sample'
  gi_1000g_g0m_g1:
    bgen_dir: '/users/k2260401/alspac/genetics/gi_1000g_g0m_g1/dosage_bgen'
    sample_file: '/users/k2260401/alspac/genetics/gi_1000g_g0m_g1/swapped.sample'
